### ISSUE TITLE
[Question] 1.16.5: Eidolon Data Recipes in Original Mod

### ISSUE THREAD

**Issue by MundM2007** [InfernalCoding/EidolonDataRecipesComplete-Master#8]
Going by this commit, the 1.16.5 version of Eidolon Rebrewed does have data recipes. https://github.com/Team-Eidolon/eidolon/pull/8/commits/0d11e4791822230f96397ee4daaba885dbabec1f
So what's the advantage of this mod? Does it provide clearer syntax?
Also is the file for https://www.curseforge.com/minecraft/mc-mods/eidolon-data-recipes-complete the same as this https://www.curseforge.com/minecraft/mc-mods/eidolon-rebrewed-data-recipes with just some small changes to make it work with the rebrewed version?

**Comment by InfernalCoding** [comment]
This mod is a completed version of Quarris's original mod that adds Spell JEI Integration and Ritual Recipes. The Rebrewed version is meant for the Eidolon Rebrewed mod instead of the Eidolon Mod. Please ask questions in the mod page comments, issues is meant to help debug functional problems with the mod.

**Comment by MundM2007** [comment]
Oh I didn't even check if comments are enabled as I always assume they don't. that would be the absolute last place I would ask for any project. Will do though
